export const assetUrl = (path) => encodeURI(path);

export const ASSETS = {
  images: [
    { key: 'arrow-root-100', url: '/Arrow(Projectile)/Arrow01(100x100).png' },
    { key: 'arrow-root-32', url: '/Arrow(Projectile)/Arrow01(32x32).png' },
    {
      key: 'arrow-soldier-100',
      url: '/Characters(100x100)/Soldier/Arrow(projectile)/Arrow01(100x100).png',
    },
    {
      key: 'arrow-soldier-32',
      url: '/Characters(100x100)/Soldier/Arrow(projectile)/Arrow01(32x32).png',
    },
    { key: 'orc-sheet', url: '/Characters(100x100)/Orc/Orc/Orc.png' },
    { key: 'orc-sheet-shadowed', url: '/Characters(100x100)/Orc/Orc with shadows/Orc.png' },
    { key: 'orc-sheet-effects', url: '/Characters(100x100)/Orc/Orc(Split Effects)/Orc.png' },
    { key: 'soldier-sheet', url: '/Characters(100x100)/Soldier/Soldier/Soldier.png' },
    {
      key: 'soldier-sheet-shadowed',
      url: '/Characters(100x100)/Soldier/Soldier with shadows/Soldier.png',
    },
    {
      key: 'soldier-sheet-effects',
      url: '/Characters(100x100)/Soldier/Soldier(Split Effects)/Soldier.png',
    },
  ],
  spritesheets: [
    {
      key: 'slime',
      url: '/tilesets/slime.png',
      frameWidth: 16,
      frameHeight: 16,
    },
    {
      key: 'npc-alex',
      url: '/tilesets/spr_alex.png',
      frameWidth: 16,
      frameHeight: 32,
    },
    {
      key: 'npc-anna',
      url: '/tilesets/spr_anna.png',
      frameWidth: 16,
      frameHeight: 32,
    },
    {
      key: 'npc-ardley',
      url: '/tilesets/spr_ardley.png',
      frameWidth: 16,
      frameHeight: 32,
    },
    {
      key: 'npc-colt',
      url: '/tilesets/spr_colt.png',
      frameWidth: 16,
      frameHeight: 32,
    },
    {
      key: 'npc-ester',
      url: '/tilesets/spr_ester.png',
      frameWidth: 16,
      frameHeight: 32,
    },
    {
      key: 'npc-tom',
      url: '/tilesets/spr_tom.png',
      frameWidth: 16,
      frameHeight: 32,
    },
    {
      key: 'orc-attack1',
      url: '/Characters(100x100)/Orc/Orc/Orc-Attack01.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-attack2',
      url: '/Characters(100x100)/Orc/Orc/Orc-Attack02.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-death',
      url: '/Characters(100x100)/Orc/Orc/Orc-Death.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-hurt',
      url: '/Characters(100x100)/Orc/Orc/Orc-Hurt.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-idle',
      url: '/Characters(100x100)/Orc/Orc/Orc-Idle.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-walk',
      url: '/Characters(100x100)/Orc/Orc/Orc-Walk.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-shadow',
      url: '/Characters(100x100)/Orc/Orc/Shadow sprites/Orc-shadow.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-shadow-attack2',
      url: '/Characters(100x100)/Orc/Orc/Shadow sprites/Orc-shadow_attack02.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-shadow-death',
      url: '/Characters(100x100)/Orc/Orc/Shadow sprites/Orc-shadow_death.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-ws-attack1',
      url: '/Characters(100x100)/Orc/Orc with shadows/Orc-Attack01.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-ws-attack2',
      url: '/Characters(100x100)/Orc/Orc with shadows/Orc-Attack02.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-ws-death',
      url: '/Characters(100x100)/Orc/Orc with shadows/Orc-Death.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-ws-hurt',
      url: '/Characters(100x100)/Orc/Orc with shadows/Orc-Hurt.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-ws-idle',
      url: '/Characters(100x100)/Orc/Orc with shadows/Orc-Idle.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-ws-walk',
      url: '/Characters(100x100)/Orc/Orc with shadows/Orc-Walk.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-effect-attack1',
      url: '/Characters(100x100)/Orc/Orc(Split Effects)/Orc-attack01_Effect.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'orc-effect-attack2',
      url: '/Characters(100x100)/Orc/Orc(Split Effects)/Orc-attack02_Effect.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-attack1',
      url: '/Characters(100x100)/Soldier/Soldier/Soldier-Attack01.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-attack2',
      url: '/Characters(100x100)/Soldier/Soldier/Soldier-Attack02.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-attack3',
      url: '/Characters(100x100)/Soldier/Soldier/Soldier-Attack03.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-death',
      url: '/Characters(100x100)/Soldier/Soldier/Soldier-Death.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-hurt',
      url: '/Characters(100x100)/Soldier/Soldier/Soldier-Hurt.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-idle',
      url: '/Characters(100x100)/Soldier/Soldier/Soldier-Idle.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-walk',
      url: '/Characters(100x100)/Soldier/Soldier/Soldier-Walk.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-shadow-attack2',
      url: '/Characters(100x100)/Soldier/Soldier/Soldier-Shadow_attack2.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-shadow',
      url: '/Characters(100x100)/Soldier/Soldier/Shadow sprites/Soldier-Shadow.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-shadow-death',
      url: '/Characters(100x100)/Soldier/Soldier/Shadow sprites/Soldier-Shadow_death.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-ws-attack1',
      url: '/Characters(100x100)/Soldier/Soldier with shadows/Soldier-Attack01.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-ws-attack2',
      url: '/Characters(100x100)/Soldier/Soldier with shadows/Soldier-Attack02.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-ws-attack3',
      url: '/Characters(100x100)/Soldier/Soldier with shadows/Soldier-Attack03.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-ws-death',
      url: '/Characters(100x100)/Soldier/Soldier with shadows/Soldier-Death.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-ws-hurt',
      url: '/Characters(100x100)/Soldier/Soldier with shadows/Soldier-Hurt.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-ws-idle',
      url: '/Characters(100x100)/Soldier/Soldier with shadows/Soldier-Idle.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-ws-walk',
      url: '/Characters(100x100)/Soldier/Soldier with shadows/Soldier-Walk.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-effect-attack1',
      url: '/Characters(100x100)/Soldier/Soldier(Split Effects)/Soldier-Attack01_Effect.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-effect-attack2',
      url: '/Characters(100x100)/Soldier/Soldier(Split Effects)/Soldier-Attack02_Effect.png',
      frameWidth: 100,
      frameHeight: 100,
    },
    {
      key: 'soldier-effect-attack3',
      url: '/Characters(100x100)/Soldier/Soldier(Split Effects)/Soldier-Attack03_Effect.png',
      frameWidth: 100,
      frameHeight: 100,
    },
  ],
  svgs: [{ key: 'vite-logo', url: '/vite.svg' }],
  binaries: [
    { key: 'aseprite-orc', url: '/Aseprite file/Orc.aseprite' },
    { key: 'aseprite-soldier', url: '/Aseprite file/Soldier.aseprite' },
  ],
};
